//achievement
export const NEW_ACHIEVEMENT_EARN = 'NEW_ACHIEVEMENT_EARN'
export const LOAD_ACHIEVEMENT_STATS = 'LOAD_ACHIEVEMENT_STATS'

//filter 
export const ADD_FILTER_TYPE = 'ADD_FILTER_TYPE'
export const REMOVE_FILTER_TYPE = 'REMOVE_FILTER_TYPE'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const GET_TYPES = 'GET_TYPES'
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS'
export const GET_TYPES_FAILURE = 'GET_TYPES_FAILURE'

//tests
export const GET_TESTS = 'GET_TESTS'
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS'
export const GET_TESTS_FAILURE = 'GET_TESTS_FAILURE'
export const SET_TESTS = 'SET_TESTS'
export const START_TEST = 'START_TEST'
export const CORRECT_ANSWER = 'CORRECT_ANSWER'
export const NEXT_QUESTION = 'NEXT_QUESTION'
export const TEST_EXIT = 'TEST_EXIT'

//user
export const SET_TEST_STATS = 'SET_TEST_STATS'
export const UPDATE_TEST_STATS = 'UPDATE_TEST_STATS'
export const UPDATE_PASSED_COUNT = 'UPDATE_PASSED_COUNT'
export const UPDATE_PERFECT_COUNT = 'UPDATE_PERFECT_COUNT'
export const UPDATE_ACHIEVEMENTS_COUNT = 'UPDATE_ACHIEVEMENTS_COUNT'
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION'